---
title: "User Coverage by Municipality"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(rmapshaper)
library(tmap)
tmap_mode("view")

points <- st_read("~/research/randomsummerpoints.shp")
munis <- st_read("/Users/jonkent/Downloads/SIGLIM_Publico_INSPIRE/SHP_ETRS89/recintos_municipales_inspire_peninbal_etrs89/recintos_municipales_inspire_peninbal_etrs89.shp") %>% select(NAMEUNIT,geometry)
munis <- st_transform(munis, "+proj=longlat +ellps=WGS84 +datum=WGS84")
munis$bt_count <- lengths(st_intersects(munis, points))

tweets <- read_csv("~/research/tweets_jul1_sep15.csv")
tweets <- tweets %>% st_as_sf(coords = c("lon", "lat"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84")
munis$tw_count <- lengths(st_intersects(munis, tweets))

munis <- rmapshaper::ms_simplify(munis, keep = 0.01, keep_shapes = TRUE)

munis$bt_pct <- munis$bt_count/sum(munis$bt_count)
munis$tw_pct <- munis$tw_count/sum(munis$tw_count)
munis$bt_vs_tweets <- munis$bt_pct - munis$tw_pct

munis$z_tweets <- round((munis$bt_vs_tweets - mean(munis$bt_vs_tweets, na.rm=T)) / sd(munis$bt_vs_tweets, na.rm=T),1)
munis$z_tweets <- ifelse(munis$z_tweets>2,2,munis$z_tweets)
munis$z_tweets <- ifelse(munis$z_tweets < -2,-2,munis$z_tweets)

munidata <- read_csv("~/research/munipopincome.csv") %>% select(-income)
names(munidata)[1] <- "NAMEUNIT"
munis <- munis %>% left_join(munidata, by = "NAMEUNIT")
munis$pop_pct <- munis$population/sum(munis$population, na.rm = T)
munis$bt_vs_pop <- munis$bt_pct - munis$pop_pct
munis$z_pop <- round((munis$bt_vs_pop - mean(munis$bt_vs_pop, na.rm=T)) / sd(munis$bt_vs_pop, na.rm=T),1)
munis$z_pop <- ifelse(munis$z_pop>2,2,munis$z_pop)
munis$z_pop <- ifelse(munis$z_pop < -2,-2,munis$z_pop)

baseline_Twitter <- munis %>% select(NAMEUNIT,z_tweets,geometry)
names(baseline_Twitter)[2] <- "Coverage"
baseline_Population <- munis %>% select(NAMEUNIT, z_pop, geometry)
names(baseline_Population)[2] <- "Coverage"
```


```{r echo=F, warning=F, message=F, out.width = '100%', out.height = 700}
map <- tm_basemap("Esri.WorldTopoMap") +
  tm_shape(baseline_Twitter) + tm_fill("Coverage", alpha = .50) +
  tm_shape(baseline_Population) + tm_fill("Coverage", alpha = .50)

map %>% 
  tmap_leaflet() %>%
  leaflet::hideGroup("baseline_Population")
```

