---
title: "Segregation Test"
author: "Jonathan Kent"
date: "2023-03-24"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(segregation)
library(lme4)
library(lmerTest)
#library(essurvey)
library(sjPlot)
#library(sf)

options(dplyr.summarise.inform=F)

setwd("/Volumes/GoogleDrive-108577714246916192597/My\ Drive/segregation_europe")

eu_countries <- bind_rows(
  tibble(origin = c("BEL","FRA","DEU","ITA","LUX","NLD","DNK","IRL","GBR","GRC","PRT","ESP","AUT","FIN","SWE"), type = "eu_15"),
  tibble(origin = c("CYP","CZE","EST","HUN","LVA","LTU","MLT","POL","SVK","SVN","BGR","ROU","HRV"), type = "eu_exp"))


list_eu_15 <- c("BE", "DK", "DE", "IE", "GR", "ES", "FR", "IT", "LU", "NL", "AT", "PT", "FI", "SE", "GB")
list_eu_exp <- c("BG", "CZ", "EE", "HR", "CY", "LV", "LT", "HU", "MT", "PL", "RO", "SI", "SK")

d <- read_csv("~/data/ess.csv") %>% left_join(read_rds("data/l1_seg.rds") %>% rename(region = nuts2)) %>% left_join(read_rds("data/l1_pop.rds")) %>% mutate(pop_eu_all = pop_eu_15 + pop_eu_exp, pop_overall = pop_eu_all + pop_other, female = ifelse(gndr==2,1,0), age = ifelse(name=="ESS6e02_4",2012-yrbrn,2014-yrbrn), cntbrth_eu28 = ifelse(brncntr==1,"native",ifelse(cntbrthc %in% list_eu_15,"eu_15",ifelse(cntbrthc %in% list_eu_exp,"eu_exp","other"))), wt = dweight*pweight, euftf = ifelse(euftf>10,NA,euftf), age = ifelse(age<18,NA,age), eduyrs = ifelse(eduyrs>51,NA,eduyrs), cntbrth_eu28 = relevel(as.factor(cntbrth_eu28), ref = "native"))
source("~/research/oesch_class.r")
```


```{r models, warning=F}
high_seg <- lmer(euftf ~ pop_eu_15 + pop_eu_exp + pop_other + cntbrth_eu28 + female + age + I(age^2) + eduyrs + I(eduyrs^2) + class5 + (1|cntry/region), data = filter(d,eu_exp>median(d$eu_exp,na.rm = T)), weights = wt)

low_seg <- lmer(euftf ~ pop_eu_15 + pop_eu_exp + pop_other + cntbrth_eu28 + female + age + I(age^2) + eduyrs + I(eduyrs^2) + class5 + (1|cntry/region), data = filter(d,eu_exp<median(d$eu_exp,na.rm = T)), weights = wt)
```


```{r plot, echo=FALSE}
p.m1 <- plot_model(high_seg, 
           terms = c("pop_eu_15", "pop_eu_exp", "pop_other"), 
           title = "High Seg.",
           show.values = T,
           vline.color = "black")
levels(p.m1$data$term) <- c("Pop. Other","Pop. EU East","Pop. EU West")
p.m1$data$p.label <- str_remove_all(p.m1$data$p.label,"[-|.| |[:digit:]]")
p.m1 <- p.m1 + theme(text = element_text(size = 18), axis.text.x = element_text(size = 10)) 

p.m2 <- plot_model(low_seg, 
           terms = c("pop_eu_15", "pop_eu_exp", "pop_other"), 
           title = "Low Seg.",
           show.values = T,
           vline.color = "black")
levels(p.m2$data$term) <- c("Pop. Other","Pop. EU East","Pop. EU West")
p.m2$data$p.label <- str_remove_all(p.m2$data$p.label,"[-|.| |[:digit:]]")
p.m2 <- p.m2 + theme(text = element_text(size = 18), axis.text.x = element_text(size = 10)) 

ggpubr::ggarrange(p.m1,p.m2, nrow = 1)
```

```{r model_print, warning=F}
summary(high_seg)

summary(low_seg)
```